### PR TITLE
Adding glob python files

### PR DESCRIPTION
**Pull request by WesleyTheGeolien**
Hey,

I haven't tried this out locally so hope it works.

The current extension will run servable notebooks, in the same manner it is possible to serve python files as well I believe, hopefully this can be intergrated into the extension.

### CODE REVIEW

**Comment by WesleyTheGeolien** [comment]
I am not sure the build failure is down to me

**Comment by philippjfr** [comment]
It's not we should migrate this repo to GH Actions like all the others.

**Comment by MarcSkovMadsen** [comment]
Thanks a lot.

Do you know if it is possible to `panel serve` files in all subfolders? Or only in the root folder?

**Comment by WesleyTheGeolien** [comment]
@MarcSkovMadsen The PR I put in will only serve the (notebooks and) python files in root feel free to add another PR

**Comment by MarcSkovMadsen** [comment]
Thanks @WesleyTheGeolien . Do you have any idea on how to serve files  .py and .ipynb in any subfolder? As I see it that is not technically possible??

**Comment by philippjfr** [comment]
I think using `glob.glob('**/*.py', recursive=True)` should do it.

**Comment by philippjfr** [comment]
@WesleyTheGeolien Gave you access to the repo, since I think you might need to make a branch on the repo itself to kick off the GH Actions builds.

**Comment by MarcSkovMadsen** [comment]
Please note @WesleyTheGeolien . I believe glob(...) will fail if there are no files of the specified type. So I think this use case should be tested before deployment. At least that is what I experienced when creating a custom version of this.

**Comment by philippjfr** [comment]
Superseded by https://github.com/holoviz/jupyter-panel-proxy/pull/17. Thanks for your efforts here @WesleyTheGeolien!

**Pull request closed without merging**
